# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiprint.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiPrint(object):
    def setupUi(self, MultiPrint):
        MultiPrint.setObjectName("MultiPrint")
        MultiPrint.resize(1228, 738)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MultiPrint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_22 = QtWidgets.QWidget(MultiPrint)
        self.widget_22.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_3.addWidget(self.widget_22)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_9 = QtWidgets.QFrame(MultiPrint)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.label_41 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_2.addWidget(self.label_41)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_hunhe = QtWidgets.QWidget(MultiPrint)
        self.widget_hunhe.setObjectName("widget_hunhe")
        self.horizontalLayout_4.addWidget(self.widget_hunhe)
        self.widget_inject_1 = QtWidgets.QWidget(MultiPrint)
        self.widget_inject_1.setObjectName("widget_inject_1")
        self.horizontalLayout_4.addWidget(self.widget_inject_1)
        self.widget_inject_2 = QtWidgets.QWidget(MultiPrint)
        self.widget_inject_2.setObjectName("widget_inject_2")
        self.horizontalLayout_4.addWidget(self.widget_inject_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_11 = QtWidgets.QFrame(MultiPrint)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_2.addWidget(self.line_11)
        self.line_10 = QtWidgets.QFrame(MultiPrint)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.label_45 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_45.setObjectName("label_45")
        self.verticalLayout_2.addWidget(self.label_45)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_47 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(MultiPrint)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 2, 0, 1, 1)
        self.label_volume_inject1 = QtWidgets.QLabel(MultiPrint)
        self.label_volume_inject1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_inject1.setObjectName("label_volume_inject1")
        self.gridLayout.addWidget(self.label_volume_inject1, 2, 1, 1, 1)
        self.label_volume_inject2 = QtWidgets.QLabel(MultiPrint)
        self.label_volume_inject2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_inject2.setObjectName("label_volume_inject2")
        self.gridLayout.addWidget(self.label_volume_inject2, 2, 2, 1, 1)
        self.tb_material_inject1 = QtWidgets.QLineEdit(MultiPrint)
        self.tb_material_inject1.setObjectName("tb_material_inject1")
        self.gridLayout.addWidget(self.tb_material_inject1, 1, 1, 1, 1)
        self.tb_material_inject2 = QtWidgets.QLineEdit(MultiPrint)
        self.tb_material_inject2.setObjectName("tb_material_inject2")
        self.gridLayout.addWidget(self.tb_material_inject2, 1, 2, 1, 1)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_12 = QtWidgets.QFrame(MultiPrint)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.line_13 = QtWidgets.QFrame(MultiPrint)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_2.addWidget(self.line_13)
        self.label_52 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_52.setObjectName("label_52")
        self.verticalLayout_2.addWidget(self.label_52)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.line_14 = QtWidgets.QFrame(MultiPrint)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_2.addWidget(self.line_14)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 10)
        self.verticalLayout_2.setStretch(7, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout_2.setStretch(10, 10)
        self.verticalLayout_2.setStretch(11, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tb_layer = QtWidgets.QLineEdit(MultiPrint)
        self.tb_layer.setAlignment(QtCore.Qt.AlignCenter)
        self.tb_layer.setObjectName("tb_layer")
        self.verticalLayout_4.addWidget(self.tb_layer)
        self.slider_layer = QtWidgets.QSlider(MultiPrint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_layer.sizePolicy().hasHeightForWidth())
        self.slider_layer.setSizePolicy(sizePolicy)
        self.slider_layer.setMinimum(1)
        self.slider_layer.setOrientation(QtCore.Qt.Vertical)
        self.slider_layer.setObjectName("slider_layer")
        self.verticalLayout_4.addWidget(self.slider_layer)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_30 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.cb_munnal = QtWidgets.QCheckBox(MultiPrint)
        self.cb_munnal.setIconSize(QtCore.QSize(25, 25))
        self.cb_munnal.setObjectName("cb_munnal")
        self.verticalLayout_5.addWidget(self.cb_munnal)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line = QtWidgets.QFrame(MultiPrint)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.label_31 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_9.addWidget(self.label_31)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_inject1_takeout = QtWidgets.QPushButton(MultiPrint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_inject1_takeout.sizePolicy().hasHeightForWidth())
        self.btn_inject1_takeout.setSizePolicy(sizePolicy)
        self.btn_inject1_takeout.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_inject1_takeout.setObjectName("btn_inject1_takeout")
        self.verticalLayout_11.addWidget(self.btn_inject1_takeout)
        self.btn_inject1_enject = QtWidgets.QPushButton(MultiPrint)
        self.btn_inject1_enject.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_inject1_enject.setObjectName("btn_inject1_enject")
        self.verticalLayout_11.addWidget(self.btn_inject1_enject)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.tb_inject1_volume = QtWidgets.QLineEdit(MultiPrint)
        self.tb_inject1_volume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb_inject1_volume.setObjectName("tb_inject1_volume")
        self.horizontalLayout.addWidget(self.tb_inject1_volume)
        self.label_35 = QtWidgets.QLabel(MultiPrint)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout.addWidget(self.label_35)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 5)
        self.horizontalLayout.setStretch(4, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(MultiPrint)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 10)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.line_3 = QtWidgets.QFrame(MultiPrint)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.label_32 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_8.addWidget(self.label_32)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_inject2_takeout = QtWidgets.QPushButton(MultiPrint)
        self.btn_inject2_takeout.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_inject2_takeout.setObjectName("btn_inject2_takeout")
        self.verticalLayout_12.addWidget(self.btn_inject2_takeout)
        self.btn_inject2_enject = QtWidgets.QPushButton(MultiPrint)
        self.btn_inject2_enject.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_inject2_enject.setObjectName("btn_inject2_enject")
        self.verticalLayout_12.addWidget(self.btn_inject2_enject)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.tb_inject2_volume = QtWidgets.QLineEdit(MultiPrint)
        self.tb_inject2_volume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb_inject2_volume.setObjectName("tb_inject2_volume")
        self.horizontalLayout_6.addWidget(self.tb_inject2_volume)
        self.label_36 = QtWidgets.QLabel(MultiPrint)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 5)
        self.horizontalLayout_6.setStretch(3, 5)
        self.horizontalLayout_6.setStretch(4, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.line_4 = QtWidgets.QFrame(MultiPrint)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 2)
        self.verticalLayout_8.setStretch(2, 10)
        self.verticalLayout_8.setStretch(3, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_5 = QtWidgets.QFrame(MultiPrint)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.label_33 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_7.addWidget(self.label_33)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.btn_peristaltic_1 = QtWidgets.QPushButton(MultiPrint)
        self.btn_peristaltic_1.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_peristaltic_1.setObjectName("btn_peristaltic_1")
        self.horizontalLayout_8.addWidget(self.btn_peristaltic_1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.btn_peristaltic_both = QtWidgets.QPushButton(MultiPrint)
        self.btn_peristaltic_both.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_peristaltic_both.setObjectName("btn_peristaltic_both")
        self.horizontalLayout_8.addWidget(self.btn_peristaltic_both)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.btn_peristaltic_2 = QtWidgets.QPushButton(MultiPrint)
        self.btn_peristaltic_2.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_peristaltic_2.setObjectName("btn_peristaltic_2")
        self.horizontalLayout_8.addWidget(self.btn_peristaltic_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.line_6 = QtWidgets.QFrame(MultiPrint)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 2)
        self.verticalLayout_7.setStretch(3, 10)
        self.verticalLayout_7.setStretch(4, 1)
        self.verticalLayout_7.setStretch(5, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_7 = QtWidgets.QFrame(MultiPrint)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_6.addWidget(self.line_7)
        self.label_34 = QtWidgets.QLabel(MultiPrint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rb_x = QtWidgets.QRadioButton(MultiPrint)
        self.rb_x.setChecked(True)
        self.rb_x.setObjectName("rb_x")
        self.horizontalLayout_9.addWidget(self.rb_x)
        self.rb_y = QtWidgets.QRadioButton(MultiPrint)
        self.rb_y.setObjectName("rb_y")
        self.horizontalLayout_9.addWidget(self.rb_y)
        self.rb_z = QtWidgets.QRadioButton(MultiPrint)
        self.rb_z.setObjectName("rb_z")
        self.horizontalLayout_9.addWidget(self.rb_z)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_37 = QtWidgets.QLabel(MultiPrint)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_10.addWidget(self.label_37)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.Move_relative_add = QtWidgets.QPushButton(MultiPrint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Move_relative_add.sizePolicy().hasHeightForWidth())
        self.Move_relative_add.setSizePolicy(sizePolicy)
        self.Move_relative_add.setMinimumSize(QtCore.QSize(15, 15))
        self.Move_relative_add.setSizeIncrement(QtCore.QSize(40, 40))
        self.Move_relative_add.setObjectName("Move_relative_add")
        self.horizontalLayout_10.addWidget(self.Move_relative_add)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.btn_zero = QtWidgets.QPushButton(MultiPrint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_zero.sizePolicy().hasHeightForWidth())
        self.btn_zero.setSizePolicy(sizePolicy)
        self.btn_zero.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_zero.setObjectName("btn_zero")
        self.horizontalLayout_10.addWidget(self.btn_zero)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.Move_relative_positive = QtWidgets.QPushButton(MultiPrint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Move_relative_positive.sizePolicy().hasHeightForWidth())
        self.Move_relative_positive.setSizePolicy(sizePolicy)
        self.Move_relative_positive.setMinimumSize(QtCore.QSize(30, 30))
        self.Move_relative_positive.setSizeIncrement(QtCore.QSize(40, 40))
        self.Move_relative_positive.setObjectName("Move_relative_positive")
        self.horizontalLayout_10.addWidget(self.Move_relative_positive)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.horizontalLayout_10.setStretch(0, 5)
        self.horizontalLayout_10.setStretch(1, 3)
        self.horizontalLayout_10.setStretch(2, 5)
        self.horizontalLayout_10.setStretch(3, 3)
        self.horizontalLayout_10.setStretch(4, 3)
        self.horizontalLayout_10.setStretch(5, 3)
        self.horizontalLayout_10.setStretch(6, 5)
        self.horizontalLayout_10.setStretch(7, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_38 = QtWidgets.QLabel(MultiPrint)
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_11.addWidget(self.label_38)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_move_positive = QtWidgets.QPushButton(MultiPrint)
        self.btn_move_positive.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_move_positive.setObjectName("btn_move_positive")
        self.verticalLayout_13.addWidget(self.btn_move_positive)
        self.btn_move_nagative = QtWidgets.QPushButton(MultiPrint)
        self.btn_move_nagative.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_move_nagative.setObjectName("btn_move_nagative")
        self.verticalLayout_13.addWidget(self.btn_move_nagative)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.label_39 = QtWidgets.QLabel(MultiPrint)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_11.addWidget(self.label_39)
        self.tb_move = QtWidgets.QLineEdit(MultiPrint)
        self.tb_move.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb_move.setObjectName("tb_move")
        self.horizontalLayout_11.addWidget(self.tb_move)
        self.label_40 = QtWidgets.QLabel(MultiPrint)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_11.addWidget(self.label_40)
        self.horizontalLayout_11.setStretch(0, 5)
        self.horizontalLayout_11.setStretch(1, 5)
        self.horizontalLayout_11.setStretch(2, 2)
        self.horizontalLayout_11.setStretch(3, 5)
        self.horizontalLayout_11.setStretch(4, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.line_8 = QtWidgets.QFrame(MultiPrint)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_6.addWidget(self.line_8)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 5)
        self.verticalLayout_6.setStretch(4, 1)
        self.verticalLayout_6.setStretch(5, 3)
        self.verticalLayout_6.setStretch(6, 5)
        self.verticalLayout_6.setStretch(7, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 5)
        self.verticalLayout_5.setStretch(3, 5)
        self.verticalLayout_5.setStretch(4, 4)
        self.verticalLayout_5.setStretch(5, 12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.setStretch(0, 7)
        self.horizontalLayout_7.setStretch(1, 20)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayou_statust = QtWidgets.QHBoxLayout()
        self.horizontalLayou_statust.setSpacing(0)
        self.horizontalLayou_statust.setObjectName("horizontalLayou_statust")
        self.label_16 = QtWidgets.QLabel(MultiPrint)
        self.label_16.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayou_statust.addWidget(self.label_16)
        self.label_status = QtWidgets.QLabel(MultiPrint)
        self.label_status.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.horizontalLayou_statust.addWidget(self.label_status)
        self.label_17 = QtWidgets.QLabel(MultiPrint)
        self.label_17.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayou_statust.addWidget(self.label_17)
        self.label_15 = QtWidgets.QLabel(MultiPrint)
        self.label_15.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayou_statust.addWidget(self.label_15)
        self.label_process_layer = QtWidgets.QLabel(MultiPrint)
        self.label_process_layer.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_process_layer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process_layer.setObjectName("label_process_layer")
        self.horizontalLayou_statust.addWidget(self.label_process_layer)
        self.label_9 = QtWidgets.QLabel(MultiPrint)
        self.label_9.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayou_statust.addWidget(self.label_9)
        self.label_process_totallayer = QtWidgets.QLabel(MultiPrint)
        self.label_process_totallayer.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_process_totallayer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process_totallayer.setObjectName("label_process_totallayer")
        self.horizontalLayou_statust.addWidget(self.label_process_totallayer)
        self.label_13 = QtWidgets.QLabel(MultiPrint)
        self.label_13.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayou_statust.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(MultiPrint)
        self.label_11.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayou_statust.addWidget(self.label_11)
        self.label_temperature = QtWidgets.QLabel(MultiPrint)
        self.label_temperature.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temperature.setObjectName("label_temperature")
        self.horizontalLayou_statust.addWidget(self.label_temperature)
        self.label_8 = QtWidgets.QLabel(MultiPrint)
        self.label_8.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayou_statust.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(MultiPrint)
        self.label_7.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayou_statust.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(MultiPrint)
        self.label_6.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayou_statust.addWidget(self.label_6)
        self.label_process_time_hour = QtWidgets.QLabel(MultiPrint)
        self.label_process_time_hour.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_process_time_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process_time_hour.setObjectName("label_process_time_hour")
        self.horizontalLayou_statust.addWidget(self.label_process_time_hour)
        self.label_21 = QtWidgets.QLabel(MultiPrint)
        self.label_21.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayou_statust.addWidget(self.label_21)
        self.label_process_totaltime_hour = QtWidgets.QLabel(MultiPrint)
        self.label_process_totaltime_hour.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_process_totaltime_hour.setAlignment(QtCore.Qt.AlignCenter)
        self.label_process_totaltime_hour.setObjectName("label_process_totaltime_hour")
        self.horizontalLayou_statust.addWidget(self.label_process_totaltime_hour)
        self.label_2 = QtWidgets.QLabel(MultiPrint)
        self.label_2.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayou_statust.addWidget(self.label_2)
        self.label_27 = QtWidgets.QLabel(MultiPrint)
        self.label_27.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayou_statust.addWidget(self.label_27)
        self.label_complete = QtWidgets.QLabel(MultiPrint)
        self.label_complete.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_complete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_complete.setObjectName("label_complete")
        self.horizontalLayou_statust.addWidget(self.label_complete)
        self.label_29 = QtWidgets.QLabel(MultiPrint)
        self.label_29.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayou_statust.addWidget(self.label_29)
        self.label_26 = QtWidgets.QLabel(MultiPrint)
        self.label_26.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayou_statust.addWidget(self.label_26)
        self.label_25 = QtWidgets.QLabel(MultiPrint)
        self.label_25.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayou_statust.addWidget(self.label_25)
        self.label_register = QtWidgets.QLabel(MultiPrint)
        self.label_register.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.label_register.setObjectName("label_register")
        self.horizontalLayou_statust.addWidget(self.label_register)
        self.horizontalLayou_statust.setStretch(0, 10)
        self.horizontalLayou_statust.setStretch(1, 5)
        self.horizontalLayou_statust.setStretch(2, 5)
        self.horizontalLayou_statust.setStretch(3, 5)
        self.horizontalLayou_statust.setStretch(4, 10)
        self.horizontalLayou_statust.setStretch(5, 2)
        self.horizontalLayou_statust.setStretch(6, 10)
        self.horizontalLayou_statust.setStretch(7, 5)
        self.horizontalLayou_statust.setStretch(8, 5)
        self.horizontalLayou_statust.setStretch(9, 5)
        self.horizontalLayou_statust.setStretch(10, 2)
        self.horizontalLayou_statust.setStretch(11, 5)
        self.horizontalLayou_statust.setStretch(12, 5)
        self.horizontalLayou_statust.setStretch(13, 10)
        self.horizontalLayou_statust.setStretch(14, 2)
        self.horizontalLayou_statust.setStretch(15, 10)
        self.horizontalLayou_statust.setStretch(16, 5)
        self.horizontalLayou_statust.setStretch(17, 5)
        self.horizontalLayou_statust.setStretch(18, 5)
        self.horizontalLayou_statust.setStretch(19, 2)
        self.horizontalLayou_statust.setStretch(20, 2)
        self.horizontalLayou_statust.setStretch(21, 5)
        self.horizontalLayou_statust.setStretch(22, 10)
        self.verticalLayout.addLayout(self.horizontalLayou_statust)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MultiPrint)
        QtCore.QMetaObject.connectSlotsByName(MultiPrint)

    def retranslateUi(self, MultiPrint):
        _translate = QtCore.QCoreApplication.translate
        MultiPrint.setWindowTitle(_translate("MultiPrint", "Form"))
        self.label_41.setText(_translate("MultiPrint", "选择打印头"))
        self.label_45.setText(_translate("MultiPrint", "设定材料"))
        self.label_47.setText(_translate("MultiPrint", "材料名称"))
        self.label_46.setText(_translate("MultiPrint", "液体容量"))
        self.label_volume_inject1.setText(_translate("MultiPrint", "0.00mL"))
        self.label_volume_inject2.setText(_translate("MultiPrint", "0.00mL"))
        self.label_52.setText(_translate("MultiPrint", "机械轴位置"))
        self.tb_layer.setText(_translate("MultiPrint", "1"))
        self.label_30.setText(_translate("MultiPrint", "手动控制"))
        self.cb_munnal.setText(_translate("MultiPrint", "切换手动控制模式"))
        self.label_31.setText(_translate("MultiPrint", "1号注射器"))
        self.btn_inject1_takeout.setText(_translate("MultiPrint", "抽"))
        self.btn_inject1_enject.setText(_translate("MultiPrint", "排"))
        self.label_35.setText(_translate("MultiPrint", "mL溶液"))
        self.label_32.setText(_translate("MultiPrint", "2号注射器"))
        self.btn_inject2_takeout.setText(_translate("MultiPrint", "抽"))
        self.btn_inject2_enject.setText(_translate("MultiPrint", "排"))
        self.label_36.setText(_translate("MultiPrint", "mL溶液"))
        self.label_33.setText(_translate("MultiPrint", "蠕动泵"))
        self.btn_peristaltic_1.setToolTip(_translate("MultiPrint", "11"))
        self.btn_peristaltic_1.setText(_translate("MultiPrint", "1号\n"
"线路"))
        self.btn_peristaltic_both.setText(_translate("MultiPrint", "混合\n"
"线路"))
        self.btn_peristaltic_2.setText(_translate("MultiPrint", "2号\n"
"线路"))
        self.label_34.setText(_translate("MultiPrint", "机械轴"))
        self.rb_x.setText(_translate("MultiPrint", "X轴"))
        self.rb_y.setText(_translate("MultiPrint", "Y轴"))
        self.rb_z.setText(_translate("MultiPrint", "Z轴"))
        self.label_37.setText(_translate("MultiPrint", "移动"))
        self.Move_relative_add.setText(_translate("MultiPrint", "<<"))
        self.btn_zero.setText(_translate("MultiPrint", "零点"))
        self.Move_relative_positive.setText(_translate("MultiPrint", ">>"))
        self.label_38.setText(_translate("MultiPrint", "步进"))
        self.btn_move_positive.setText(_translate("MultiPrint", "正轴"))
        self.btn_move_nagative.setText(_translate("MultiPrint", "负轴"))
        self.label_39.setText(_translate("MultiPrint", "移动"))
        self.label_40.setText(_translate("MultiPrint", "mm"))
        self.label_16.setText(_translate("MultiPrint", "当前状态："))
        self.label_status.setText(_translate("MultiPrint", "已停止"))
        self.label_17.setText(_translate("MultiPrint", "|"))
        self.label_15.setText(_translate("MultiPrint", "加工高度/总高度："))
        self.label_process_layer.setText(_translate("MultiPrint", "0"))
        self.label_9.setText(_translate("MultiPrint", "/"))
        self.label_process_totallayer.setText(_translate("MultiPrint", "---"))
        self.label_13.setText(_translate("MultiPrint", "|"))
        self.label_11.setText(_translate("MultiPrint", "基板温度："))
        self.label_temperature.setText(_translate("MultiPrint", "--"))
        self.label_8.setText(_translate("MultiPrint", "℃"))
        self.label_7.setText(_translate("MultiPrint", "|"))
        self.label_6.setText(_translate("MultiPrint", "加工时间/总时间："))
        self.label_process_time_hour.setText(_translate("MultiPrint", "00:00:00"))
        self.label_21.setText(_translate("MultiPrint", "/"))
        self.label_process_totaltime_hour.setText(_translate("MultiPrint", "00:00:00"))
        self.label_2.setText(_translate("MultiPrint", "|"))
        self.label_27.setText(_translate("MultiPrint", "已完成："))
        self.label_complete.setText(_translate("MultiPrint", "0"))
        self.label_29.setText(_translate("MultiPrint", "%"))
        self.label_26.setText(_translate("MultiPrint", "|"))
        self.label_25.setText(_translate("MultiPrint", "注册状态："))
        self.label_register.setText(_translate("MultiPrint", "未注册"))
