# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parasettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Parasettings(object):
    def setupUi(self, Parasettings):
        Parasettings.setObjectName("Parasettings")
        Parasettings.setWindowModality(QtCore.Qt.ApplicationModal)
        Parasettings.resize(400, 268)
        self.buttonBox = QtWidgets.QDialogButtonBox(Parasettings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Parasettings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 311, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.tb_xyspeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tb_xyspeed.setObjectName("tb_xyspeed")
        self.gridLayout_2.addWidget(self.tb_xyspeed, 1, 1, 1, 1)
        self.tb_zspeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tb_zspeed.setObjectName("tb_zspeed")
        self.gridLayout_2.addWidget(self.tb_zspeed, 2, 1, 1, 1)
        self.speed_xy = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_xy.setObjectName("speed_xy")
        self.gridLayout_2.addWidget(self.speed_xy, 1, 2, 1, 1)
        self.tb_injectspeed = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tb_injectspeed.setObjectName("tb_injectspeed")
        self.gridLayout_2.addWidget(self.tb_injectspeed, 3, 1, 1, 1)
        self.bed_temperature = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bed_temperature.setObjectName("bed_temperature")
        self.gridLayout_2.addWidget(self.bed_temperature, 0, 2, 1, 1)
        self.speed_z = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_z.setObjectName("speed_z")
        self.gridLayout_2.addWidget(self.speed_z, 2, 2, 1, 1)
        self.tb_bedtemp = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tb_bedtemp.setObjectName("tb_bedtemp")
        self.gridLayout_2.addWidget(self.tb_bedtemp, 0, 1, 1, 1)
        self.speed_inject = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_inject.setObjectName("speed_inject")
        self.gridLayout_2.addWidget(self.speed_inject, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)

        self.retranslateUi(Parasettings)
        self.buttonBox.accepted.connect(Parasettings.accept)
        self.buttonBox.rejected.connect(Parasettings.reject)
        QtCore.QMetaObject.connectSlotsByName(Parasettings)

    def retranslateUi(self, Parasettings):
        _translate = QtCore.QCoreApplication.translate
        Parasettings.setWindowTitle(_translate("Parasettings", "参数设置"))
        self.label_11.setText(_translate("Parasettings", "mm/s"))
        self.label_10.setText(_translate("Parasettings", "℃"))
        self.label_13.setText(_translate("Parasettings", "mL/s"))
        self.label_12.setText(_translate("Parasettings", "mm/s"))
        self.label.setText(_translate("Parasettings", "基板温度："))
        self.label_2.setText(_translate("Parasettings", "X/Y轴速度："))
        self.speed_xy.setText(_translate("Parasettings", "TextLabel"))
        self.bed_temperature.setText(_translate("Parasettings", "TextLabel"))
        self.speed_z.setText(_translate("Parasettings", "TextLabel"))
        self.speed_inject.setText(_translate("Parasettings", "TextLabel"))
        self.label_3.setText(_translate("Parasettings", "Z轴速度："))
        self.label_4.setText(_translate("Parasettings", "注射速度："))
